// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  sport: __t.string(),
  location: __t.string(),
  logoUrl: __t.string().name("logo_url"),
  bannerUrl: __t.string().name("banner_url"),
  description: __t.string(),
  budgetMin: __t.u64().name("budget_min"),
  budgetMax: __t.u64().name("budget_max"),
  audienceAge: __t.string().name("audience_age"),
  audienceGender: __t.string().name("audience_gender"),
  website: __t.string(),
  foundedYear: __t.u32().name("founded_year"),
});
