// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  clubId: __t.u64().name("club_id"),
  followers: __t.u64(),
  engagementRate: __t.f64().name("engagement_rate"),
  reach: __t.u64(),
  avgLikes: __t.u64().name("avg_likes"),
  avgComments: __t.u64().name("avg_comments"),
  growthPercent: __t.f64().name("growth_percent"),
  lastUpdated: __t.string().name("last_updated"),
});
