// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  brandIdentity: __t.identity().name("brand_identity"),
  clubId: __t.u64().name("club_id"),
  status: __t.string(),
  amount: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  startDate: __t.string().name("start_date"),
  endDate: __t.string().name("end_date"),
  createdAt: __t.string().name("created_at"),
});
