// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  senderIdentity: __t.identity().name("sender_identity"),
  receiverIdentity: __t.identity().name("receiver_identity"),
  dealId: __t.u64().name("deal_id"),
  content: __t.string(),
  timestamp: __t.string(),
  read: __t.bool(),
});
