// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Brand = __t.object("Brand", {
  identity: __t.identity(),
  name: __t.string(),
  email: __t.string(),
  logoUrl: __t.string(),
  sector: __t.string(),
  budget: __t.u64(),
  isOnline: __t.bool(),
});
export type Brand = __Infer<typeof Brand>;

export const Club = __t.object("Club", {
  id: __t.u64(),
  name: __t.string(),
  sport: __t.string(),
  location: __t.string(),
  logoUrl: __t.string(),
  bannerUrl: __t.string(),
  description: __t.string(),
  budgetMin: __t.u64(),
  budgetMax: __t.u64(),
  audienceAge: __t.string(),
  audienceGender: __t.string(),
  website: __t.string(),
  foundedYear: __t.u32(),
});
export type Club = __Infer<typeof Club>;

export const ClubMetrics = __t.object("ClubMetrics", {
  id: __t.u64(),
  clubId: __t.u64(),
  followers: __t.u64(),
  engagementRate: __t.f64(),
  reach: __t.u64(),
  avgLikes: __t.u64(),
  avgComments: __t.u64(),
  growthPercent: __t.f64(),
  lastUpdated: __t.string(),
});
export type ClubMetrics = __Infer<typeof ClubMetrics>;

export const Deal = __t.object("Deal", {
  id: __t.u64(),
  brandIdentity: __t.identity(),
  clubId: __t.u64(),
  status: __t.string(),
  amount: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  startDate: __t.string(),
  endDate: __t.string(),
  createdAt: __t.string(),
});
export type Deal = __Infer<typeof Deal>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  senderIdentity: __t.identity(),
  receiverIdentity: __t.identity(),
  dealId: __t.u64(),
  content: __t.string(),
  timestamp: __t.string(),
  read: __t.bool(),
});
export type Message = __Infer<typeof Message>;

export const SavedSearch = __t.object("SavedSearch", {
  id: __t.u64(),
  brandIdentity: __t.identity(),
  name: __t.string(),
  filtersJson: __t.string(),
  createdAt: __t.string(),
});
export type SavedSearch = __Infer<typeof SavedSearch>;

