// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateDealReducer from "../create_deal_reducer";
import DeleteSavedSearchReducer from "../delete_saved_search_reducer";
import MarkMessageReadReducer from "../mark_message_read_reducer";
import RegisterBrandReducer from "../register_brand_reducer";
import SaveSearchReducer from "../save_search_reducer";
import SeedDataReducer from "../seed_data_reducer";
import SendMessageReducer from "../send_message_reducer";
import UpdateDealStatusReducer from "../update_deal_status_reducer";

export type CreateDealParams = __Infer<typeof CreateDealReducer>;
export type DeleteSavedSearchParams = __Infer<typeof DeleteSavedSearchReducer>;
export type MarkMessageReadParams = __Infer<typeof MarkMessageReadReducer>;
export type RegisterBrandParams = __Infer<typeof RegisterBrandReducer>;
export type SaveSearchParams = __Infer<typeof SaveSearchReducer>;
export type SeedDataParams = __Infer<typeof SeedDataReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type UpdateDealStatusParams = __Infer<typeof UpdateDealStatusReducer>;

